"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("es6-shim");
require("zone.js/dist/zone");
require("reflect-metadata/Reflect.js");
require("@angular/http");
require("@angular/router");
require("@angular/core");
require("@angular/common");
require("rxjs");
require("bootstrap/dist/css/bootstrap.min.css");
require("jquery/dist/jquery");
require("bootstrap/dist/js/bootstrap");
require("bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css");
require("bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js");
require("bootstrap-datepicker/dist/locales/bootstrap-datepicker.es.min.js");
